"""
Big Data Recommendation System — Streamlit Dashboard
Reads precomputed parquet from output/ (generated by src/pipeline.py)
"""

import os
import json
import pandas as pd
import streamlit as st

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="RetailRocket Recommender",
    page_icon="🛒",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Custom CSS ─────────────────────────────────────────────────────────────────
st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono&display=swap');

    /* ── Base ── */
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .stApp { background: #0d0f1a; color: #e8eaf0; }

    /* ── Header ── */
    .hero {
        background: linear-gradient(135deg, #1a1f3e 0%, #0d1628 40%, #131b2e 100%);
        border: 1px solid rgba(99,102,241,0.25);
        border-radius: 20px;
        padding: 2.5rem 3rem;
        margin-bottom: 2rem;
        position: relative;
        overflow: hidden;
    }
    .hero::before {
        content: "";
        position: absolute;
        inset: 0;
        background: radial-gradient(ellipse at 70% 50%, rgba(99,102,241,0.12) 0%, transparent 70%);
        pointer-events: none;
    }
    .hero h1 {
        font-size: 2.4rem;
        font-weight: 800;
        background: linear-gradient(90deg, #818cf8, #c084fc, #fb7185);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin: 0 0 .4rem;
    }
    .hero p { color: #94a3b8; margin: 0; font-size: 1rem; font-weight: 400; }

    /* ── KPI Cards ── */
    .kpi-grid { display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem; }
    .kpi {
        flex: 1 1 160px;
        background: #13172b;
        border: 1px solid rgba(99,102,241,0.2);
        border-radius: 14px;
        padding: 1.2rem 1.4rem;
        transition: border-color .2s, transform .2s;
    }
    .kpi:hover { border-color: #818cf8; transform: translateY(-2px); }
    .kpi-label { font-size: .7rem; font-weight: 600; letter-spacing: .08em;
                 color: #64748b; text-transform: uppercase; margin-bottom: .3rem; }
    .kpi-value { font-size: 1.8rem; font-weight: 700; color: #c7d2fe; }
    .kpi-sub   { font-size: .72rem; color: #475569; margin-top: .2rem; }

    /* ── Tabs ── */
    div[data-baseweb="tab-list"] {
        background: #13172b;
        border-radius: 12px;
        padding: 4px;
        gap: 4px;
        border: 1px solid rgba(99,102,241,0.15);
    }
    div[data-baseweb="tab"] {
        border-radius: 9px !important;
        font-weight: 600 !important;
        color: #64748b !important;
        padding: .5rem 1.5rem !important;
    }
    div[aria-selected="true"][data-baseweb="tab"] {
        background: linear-gradient(135deg, #4f46e5, #7c3aed) !important;
        color: #fff !important;
    }

    /* ── Rec card ── */
    .rec-card {
        display: flex;
        align-items: center;
        gap: 1rem;
        background: #13172b;
        border: 1px solid rgba(99,102,241,0.18);
        border-radius: 12px;
        padding: .9rem 1.2rem;
        margin-bottom: .6rem;
        transition: border-color .2s, transform .15s;
    }
    .rec-card:hover { border-color: #818cf8; transform: translateX(4px); }
    .rec-rank {
        width: 32px; height: 32px;
        border-radius: 50%;
        background: linear-gradient(135deg, #4f46e5, #7c3aed);
        display: flex; align-items: center; justify-content: center;
        font-weight: 700; font-size: .85rem; color: #fff;
        flex-shrink: 0;
    }
    .rec-body { flex: 1; }
    .rec-item { font-weight: 600; font-size: .95rem; color: #e2e8f0; }
    .rec-score { font-size: .75rem; color: #64748b; margin-top: .1rem; }
    .score-bar {
        height: 4px; border-radius: 4px;
        background: linear-gradient(90deg, #4f46e5, #c084fc);
        margin-top: .35rem;
    }

    /* ── History table ── */
    .hist-row {
        display: flex; align-items: center; gap: .8rem;
        padding: .55rem .9rem;
        border-radius: 9px;
        margin-bottom: .35rem;
        background: #0d0f1a;
        border: 1px solid rgba(255,255,255,0.05);
    }
    .badge {
        display: inline-block;
        padding: .15rem .6rem;
        border-radius: 20px;
        font-size: .7rem;
        font-weight: 700;
        letter-spacing: .05em;
    }
    .badge-view        { background:#1e3a5f; color:#60a5fa; }
    .badge-addtocart   { background:#1a3328; color:#34d399; }
    .badge-transaction { background:#3b1f3f; color:#e879f9; }

    /* ── Arch diagram ── */
    .arch-step {
        background: #13172b;
        border: 1px solid rgba(99,102,241,0.2);
        border-radius: 12px;
        padding: 1rem 1.4rem;
        margin-bottom: .7rem;
        display: flex; gap: 1rem; align-items: flex-start;
    }
    .arch-icon { font-size: 1.5rem; }
    .arch-body h4 { margin: 0 0 .2rem; color: #c7d2fe; font-size: .95rem; }
    .arch-body p  { margin: 0; color: #64748b; font-size: .82rem; line-height: 1.5; }

    /* ── Section headings ── */
    .section-title {
        font-size: .7rem;
        font-weight: 700;
        letter-spacing: .1em;
        text-transform: uppercase;
        color: #4f46e5;
        margin: 1.4rem 0 .7rem;
    }

    /* ── Streamlit overrides ── */
    .stSelectbox > div { background: #13172b !important; border-color: rgba(99,102,241,0.3) !important; }
    div[data-testid="stTextInput"] input {
        background: #13172b !important;
        border: 1px solid rgba(99,102,241,0.3) !important;
        color: #e8eaf0 !important;
        border-radius: 10px !important;
    }
    footer { display: none !important; }
    #MainMenu { display: none !important; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
PARQUET_DIR = os.path.join(BASE_DIR, "output", "recommendations.parquet")
META_PATH   = os.path.join(BASE_DIR, "output", "meta.json")
EVENTS_PATH = os.path.join(BASE_DIR, "events.csv")


# ── Data Loading ───────────────────────────────────────────────────────────────
@st.cache_data(show_spinner=False)
def load_recommendations():
    return pd.read_parquet(PARQUET_DIR)


@st.cache_data(show_spinner=False)
def load_events(nrows=200_000):
    return pd.read_csv(EVENTS_PATH, nrows=nrows)


@st.cache_data(show_spinner=False)
def load_meta():
    if os.path.exists(META_PATH):
        with open(META_PATH) as f:
            return json.load(f)
    return {}


# Check pipeline output
pipeline_ready = os.path.exists(PARQUET_DIR)

# ── Hero Header ────────────────────────────────────────────────────────────────
st.markdown(
    """
    <div class="hero">
        <h1>🛒 RetailRocket Recommender</h1>
        <p>Big Data · PySpark ALS · Real-time Personalisation at Scale</p>
    </div>
    """,
    unsafe_allow_html=True,
)

if not pipeline_ready:
    st.error(
        "⚠️ **Pipeline output not found.** "
        "Run `python src/pipeline.py` first to train the model and generate recommendations.",
        icon="🚨",
    )
    st.stop()

# ── Load data ─────────────────────────────────────────────────────────────────
with st.spinner("Loading precomputed recommendations …"):
    recs_df   = load_recommendations()
    events_df = load_events()
    meta      = load_meta()

# Normalise column types
recs_df["visitorid"]          = recs_df["visitorid"].astype(str)
recs_df["recommended_itemid"] = recs_df["recommended_itemid"].astype(str)
events_df["visitorid"]        = events_df["visitorid"].astype(str)
events_df["itemid"]           = events_df["itemid"].astype(str)

all_users = sorted(recs_df["visitorid"].unique())

# ── KPI Bar ────────────────────────────────────────────────────────────────────
te = meta.get("total_events",  len(events_df))
uu = meta.get("unique_users",  recs_df["visitorid"].nunique())
ui = meta.get("unique_items",  recs_df["recommended_itemid"].nunique())
rmse_val = meta.get("rmse", "N/A")

st.markdown(
    f"""
    <div class="kpi-grid">
      <div class="kpi">
        <div class="kpi-label">Total Events</div>
        <div class="kpi-value">{te:,}</div>
        <div class="kpi-sub">Retailrocket dataset</div>
      </div>
      <div class="kpi">
        <div class="kpi-label">Unique Users</div>
        <div class="kpi-value">{uu:,}</div>
        <div class="kpi-sub">Indexed by ALS</div>
      </div>
      <div class="kpi">
        <div class="kpi-label">Unique Items</div>
        <div class="kpi-value">{ui:,}</div>
        <div class="kpi-sub">Catalogue size</div>
      </div>
      <div class="kpi">
        <div class="kpi-label">Test RMSE</div>
        <div class="kpi-value">{rmse_val}</div>
        <div class="kpi-sub">ALS model accuracy</div>
      </div>
      <div class="kpi">
        <div class="kpi-label">Rec. Rows</div>
        <div class="kpi-value">{len(recs_df):,}</div>
        <div class="kpi-sub">Top-5 per user</div>
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# ── Tabs ───────────────────────────────────────────────────────────────────────
tab1, tab2 = st.tabs(["🎯  User Simulator", "📊  Analytics & Architecture"])

# ══════════════════════════════════════════════════════════════════════════════
# TAB 1 — User Simulator
# ══════════════════════════════════════════════════════════════════════════════
with tab1:
    col_left, col_right = st.columns([1, 1.6], gap="large")

    with col_left:
        st.markdown('<div class="section-title">Select a Visitor</div>', unsafe_allow_html=True)

        search_mode = st.radio(
            "Input method",
            ["Dropdown (known users)", "Type a Visitor ID"],
            horizontal=True,
            label_visibility="collapsed",
        )

        if search_mode == "Dropdown (known users)":
            selected_user = st.selectbox(
                "Visitor ID",
                options=all_users[:5000],  # cap for perf
                label_visibility="collapsed",
            )
        else:
            selected_user = st.text_input(
                "Enter Visitor ID",
                placeholder="e.g. 1234567",
                label_visibility="collapsed",
            ).strip()

        if selected_user:
            # ── User history ──────────────────────────────────────────────────
            st.markdown('<div class="section-title">Past Activity</div>', unsafe_allow_html=True)
            history = (
                events_df[events_df["visitorid"] == str(selected_user)]
                .sort_values("timestamp", ascending=False)
                .head(10)
            )
            if history.empty:
                st.info("No historical activity found for this visitor in the sampled data.")
            else:
                badge_cls = {
                    "view":        "badge-view",
                    "addtocart":   "badge-addtocart",
                    "transaction": "badge-transaction",
                }
                rows_html = ""
                for _, row in history.iterrows():
                    ev = str(row.get("event", ""))
                    item = str(row.get("itemid", "—"))
                    cls  = badge_cls.get(ev, "badge-view")
                    rows_html += (
                        f'<div class="hist-row">'
                        f'  <span class="badge {cls}">{ev.upper()}</span>'
                        f'  <span style="color:#94a3b8;font-size:.85rem;">Item <b style="color:#e2e8f0">{item}</b></span>'
                        f'</div>'
                    )
                st.markdown(rows_html, unsafe_allow_html=True)

    with col_right:
        if selected_user:
            st.markdown('<div class="section-title">Top 5 Recommendations</div>', unsafe_allow_html=True)

            user_recs = recs_df[recs_df["visitorid"] == str(selected_user)]

            if user_recs.empty:
                st.warning(
                    "🥶 **Cold-Start User** — This visitor wasn't seen during training. "
                    "ALS cannot generate personalised recommendations for unseen users. "
                    "Consider a fallback strategy (e.g. popularity-based recs).",
                    icon="❄️",
                )
            else:
                user_recs = user_recs.sort_values("als_score", ascending=False).head(5)
                max_score = float(user_recs["als_score"].max()) if len(user_recs) else 1.0

                cards_html = ""
                for rank, (_, row) in enumerate(user_recs.iterrows(), 1):
                    score  = float(row["als_score"])
                    item   = str(row["recommended_itemid"])
                    pct    = max(5, int(score / max_score * 100))
                    cards_html += f"""
                    <div class="rec-card">
                      <div class="rec-rank">#{rank}</div>
                      <div class="rec-body">
                        <div class="rec-item">Item {item}</div>
                        <div class="rec-score">ALS confidence score: {score:.4f}</div>
                        <div class="score-bar" style="width:{pct}%;"></div>
                      </div>
                    </div>"""
                st.markdown(cards_html, unsafe_allow_html=True)

                with st.expander("🔍 Raw recommendation data"):
                    st.dataframe(
                        user_recs[["recommended_itemid", "als_score"]].reset_index(drop=True),
                        use_container_width=True,
                    )

        else:
            st.markdown(
                """
                <div style="height:100%;display:flex;align-items:center;justify-content:center;
                            flex-direction:column;gap:.5rem;padding:3rem;text-align:center;">
                  <div style="font-size:3rem;">👈</div>
                  <div style="color:#475569;font-size:.95rem;">
                    Select or enter a Visitor ID on the left<br>to see their personalised recommendations.
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )

# ══════════════════════════════════════════════════════════════════════════════
# TAB 2 — Analytics & Architecture
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    col_a, col_b = st.columns([1.2, 1], gap="large")

    with col_a:
        st.markdown('<div class="section-title">System Architecture</div>', unsafe_allow_html=True)
        arch_steps = [
            ("📥", "Data Ingestion",
             "events.csv (94 MB, ~2.7M rows) read via PySpark with inferSchema. "
             "Distributed across local cores using local[*]."),
            ("⚙️", "Preprocessing & Scoring",
             "Events mapped to implicit feedback scores: "
             "view → 1.0 · addtocart → 3.0 · transaction → 5.0. "
             "Null events dropped."),
            ("🔢", "ID Indexing",
             "PySpark StringIndexer converts visitorid → user_id_num, "
             "itemid → item_id_num (integer indices required by ALS)."),
            ("🤖", "ALS Model Training",
             "Alternating Least Squares with implicitPrefs=True. "
             "rank=20 · maxIter=10 · regParam=0.1. "
             "80/20 train/test split."),
            ("📊", "Evaluation",
             "RegressionEvaluator computes RMSE on held-out test set. "
             f"Achieved RMSE: {rmse_val}."),
            ("💾", "Parquet Output",
             "Top-5 recommendations for every user saved as Parquet. "
             "Dashboard reads this file instantly with Pandas — no Spark at query time."),
            ("🖥️", "Streamlit Dashboard",
             "Interactive UI with User Simulator & Analytics tabs. "
             "Cold-start gracefully handled with a user-friendly message."),
        ]
        for icon, title, desc in arch_steps:
            st.markdown(
                f"""<div class="arch-step">
                  <div class="arch-icon">{icon}</div>
                  <div class="arch-body"><h4>{title}</h4><p>{desc}</p></div>
                </div>""",
                unsafe_allow_html=True,
            )

    with col_b:
        st.markdown('<div class="section-title">Dataset Statistics</div>', unsafe_allow_html=True)

        event_counts = events_df["event"].value_counts()
        ec_html = ""
        colors = {"view": "#60a5fa", "addtocart": "#34d399", "transaction": "#e879f9"}
        for ev, cnt in event_counts.items():
            c = colors.get(ev, "#94a3b8")
            pct = cnt / len(events_df) * 100
            ec_html += f"""
            <div style="margin-bottom:.9rem;">
              <div style="display:flex;justify-content:space-between;margin-bottom:.3rem;">
                <span style="color:#e2e8f0;font-weight:600">{ev}</span>
                <span style="color:#64748b;font-size:.85rem">{cnt:,} ({pct:.1f}%)</span>
              </div>
              <div style="background:#1e293b;border-radius:4px;height:6px;">
                <div style="background:{c};width:{pct:.1f}%;height:6px;border-radius:4px;"></div>
              </div>
            </div>"""
        st.markdown(ec_html, unsafe_allow_html=True)

        st.markdown('<div class="section-title">Model Hyperparameters</div>', unsafe_allow_html=True)
        params = {
            "Algorithm":         "ALS (Alternating Least Squares)",
            "Implicit Prefs":    str(meta.get("implicit_prefs", True)),
            "Rank":              meta.get("als_rank", 20),
            "Max Iterations":    meta.get("als_maxIter", 10),
            "Regularisation λ":  meta.get("als_regParam", 0.1),
            "Cold Start":        "drop",
            "Train Split":       "80%",
            "Test Split":        "20%",
            "Test RMSE":         rmse_val,
        }
        rows = "".join(
            f"<tr><td style='padding:.45rem .8rem;color:#64748b;font-size:.82rem'>{k}</td>"
            f"<td style='padding:.45rem .8rem;color:#c7d2fe;font-size:.82rem;font-weight:600'>{v}</td></tr>"
            for k, v in params.items()
        )
        st.markdown(
            f"""<table style="width:100%;border-collapse:collapse;background:#13172b;
                              border:1px solid rgba(99,102,241,0.18);border-radius:12px;overflow:hidden">
                {rows}
                </table>""",
            unsafe_allow_html=True,
        )
